name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute shell script
        run: |
          chmod + ./ascii-script.sh
          ./ascii-script.sh