name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, alpine]
        # exclude:
        #   - image: alpine
        #     os: windows-latest
        include:
          - image: amd64/alpine
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details from ${{ matrix.os }}
        run: docker info

      - name: Run Image ${{ matrix.image }} on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}