name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details from ${{ matrix.os }}
        run: docker info

      - name: Run Image ${{ matrix.image }} on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}